### ISSUE TITLE
Visitor Successfully Signs Up for an Account

### ISSUE THREAD

**Issue by ChrisCenatie** [russelleh/denvestments#1]
As a visitor
When I visit Denvestments home-page
And I click on Create an Account
And I am redirected to the Create an Account page where I enter a username (email) and password
Then I am redirected to home page 
and see that I'm signed in.

As a visitor
When I visit Denvestments home-page
And I click on Create an Account
And I am redirected to the Create an Account page where I enter an incorrect username (email) or password
Then I the create account page is rendered noting that password or email was entered incorrectly

**Comment by mbburch** [comment]
Closes #1 Use Mike's user story instead
