### ISSUE TITLE
Adding loans to the cart

### ISSUE THREAD

**Issue by mikedao** [russelleh/denvestments#41]
Background: Loans, and a user that is not logged in

Title: 

As a visitor
When I visit any page with an loan on it
I should see a link or button for "Add to Cart"
When I click "Add to cart" for that loan
And I click a link or button to view cart
And my current path should be "/cart"
And I should see a small image, title, description and price for the loan I just added
And there should be a "total" price for the cart that should be the sum of all loans in the cart

When I login
And I visit "/cart"
Then I should see all of the data that was there when I was not logged in

**Comment by ChrisCenatie** [comment]
Everything completed, still need to add login and pics
